name: Build docker image

on:
  push:
    branches:
      - master
  pull_request:
  create:
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: docker/Dockerfile
